[package]
name = "ws-1in5-i2c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.14.1"
num-traits = "0.2.15"
rusttype = "0.9.3"
imageproc = "0.23.0"
image = "0.24.5"